name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy to ECS
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="docker_image=${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAWIVDCUIS6HEZNZLR }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.+Ya6X94Y4LReVYuR1OELIEDdxGPpIr1PU7AZQu9Y }}
